coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project: no
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "*.h"
  - "src/test/**"           # ignore test harness code
  - "src/den2obj.cpp"       # ignore main routine of den2obj
  - "src/generator.cpp"     # not being tested, also only used for dataset generation