name: OpenVDB module

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y build-essential cmake libglm-dev libtclap-dev libboost-all-dev libopenvdb-dev libtbb-dev libcppunit-dev libeigen3-dev wget
    - name: Get sources OpenVDB 8.2
      run: wget https://github.com/AcademySoftwareFoundation/openvdb/archive/refs/tags/v8.2.0.tar.gz && tar -xvzf v8.2.0.tar.gz
    - name: Compile and install OpenVDB 8.02
      run: mkdir openvdb-build && cd openvdb-build && cmake ../openvdb-8.2.0 -DCMAKE_INSTALL_PREFIX=/opt/openvdb && sudo make install
    - name: Configure CMake
      run: mkdir build && cd build && cmake -DMOD_OPENVDB=1 ../src
    - name: Build
      run: cd build && make -j3
    - name: Perform unit tests
      run: cd build && make test
