name: docs

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master"]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    image: ghcr.io/ifilot/sphinx:v0.9.0
    steps:
    - name: Build documentation
      run: cd docs && make html
    - name: Upload documentation as artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: ./docs/_build/html

   deploy:
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download docs
      uses: actions/download-artifact@v3
      with:
        name: html-docs
        path: html-docs

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/ifilot/den2obj-docs-nginx

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: doc.Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}